import AuthProvider from './AuthProvider'
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'

export const metadata = {
  title: 'PeakNet',
  description: 'Generated by create next app',
  icons: {
    icon: "/icon.png",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <AuthProvider>
    <html lang="en">
      <body className='flex flex-col min-h-screen font-inter'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  </AuthProvider>
  )
}
